name: macos

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: cmake build
      run: |
        mkdir build
        cd  build
        cmake ../ -G Xcode
        cmake --build . --target ALL_BUILD --config Release
