name: ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install dependencies
      run: |
        sudo apt-get install freeglut3-dev
        sudo apt-get install libopenal-dev

    - name: cmake build
      run: |
        mkdir build
        cd  build
        cmake ../
        cmake --build .

#    - name: make
#      run: make
#      working-directory: ./project/unix
