name: windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: download freeglut
      run: curl -s -O https://www.transmissionzero.co.uk/files/software/development/GLUT/freeglut-MSVC-3.0.0-2.mp.zip

    - name: setup freeglut
      run: 7z.exe x -y freeglut-MSVC-3.0.0-2.mp.zip

    - name: download OpenAL Soft
      run: curl -s -O https://openal-soft.org/openal-binaries/openal-soft-1.21.0-bin.zip

    - name: setup OpenAL Soft
      run: 7z.exe x -y openal-soft-1.21.0-bin.zip

    - name: cmake build
      run: |
        mkdir build
        cd  build
        cmake ../ -G "Visual Studio 16" -A x64
        cmake --build . --target ALL_BUILD --config Release
